In [ ]:
# !pip install pymysql
# !pip install sqlalchemy

In [1]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

In [2]:
#db_connection_str = 'mysql+pymysql://[db유저이름]:[db password]@[host address]/[db name]'
db_connection_str = 'mysql+pymysql://root:root@localhost:3306/mydata'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

In [3]:
#Working Directory 확인
import os

current_path = os.getcwd()
current_path

'C:\\Users\\neckt'

In [4]:
#Working Directory에 csv data 넣은 경우
df_reviews = pd.read_csv('Womens Clothing E-Commerce Reviews.csv')
df_reviews

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

In [6]:
df_reviews.to_sql(name='dataset1', con=db_connection, if_exists='replace', index=False)

23486